name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend Docker image
      run: |
        docker-compose build backend
        docker tag backend:latest jonasferrao/preml:backend-latest
        docker push jonasferrao/preml:backend-latest

    - name: Build and push frontend Docker image
      run: |
        docker-compose build frontend
        docker tag frontend:latest jonasferrao/preml:frontend-latest
        docker push jonasferrao/preml:frontend-latest
